### ISSUE TITLE
1.7.0版本以及之后，有人遇到CocosCreater2.4微信小游戏真机调试TypeError: Function(...) is not a function么？

### ISSUE THREAD

**Issue by Jinngoo** [TencentCloudBase/tcb-js-sdk#22]
在微信开发者工具直接运行是可以的，但真机调试运行就会出现，1.6.1版本没事，之后都会出现，请问有人遇到么？
```
MiniProgramError
TypeError: Function(...) is not a function
TypeError: Function(...) is not a function
at  (src/assets/cloud/tcbjs/tcbjs.js:1:171219)
at call (src/assets/cloud/tcbjs/tcbjs.js:1:359)
at n (src/assets/cloud/tcbjs/tcbjs.js:1:165011)
at call (src/assets/cloud/tcbjs/tcbjs.js:1:359)
at n (src/assets/cloud/tcbjs/tcbjs.js:1:1158)
at  (src/assets/cloud/tcbjs/tcbjs.js:1:251)
at t (src/assets/cloud/tcbjs/tcbjs.js:1:81)
at  (src/assets/cloud/tcbjs/tcbjs.js:1:2)
at require (WAGameSubContext.js:2:87306)
at at (WAGameSubContext.js:2:86679)
```

**Comment by zhoujunpeng** [comment]
@Jinngoo 试一下最新版本的SDK是否还存在这个问题
