### ISSUE TITLE
Nativescript: Can't find variable: window

### ISSUE THREAD

**Issue by chenliang0571** [TencentCloudBase/tcb-js-sdk#8]
```
LOG from device iPhoneMM: CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:4160:28: ERROR Error: Uncaught (in promise): ReferenceError: Can't find variable: window
genAdapter(file:///app/vendor.js:20104:21)
at useDefaultAdapter(file:///app/vendor.js:19935:32)
at file:///app/vendor.js:21057:46
at file:///app/vendor.js:20968:36
at CloudTcbService(file:///app/bundle.js:309:67)
at CloudTcbService([native code])
at file:///app/tns_modules/@angular/core/bundles/core.umd.js:11331:108
```
出错的地方：
```javascript
function genAdapter() {
    var adapter = {
        root: window,
        reqClass: WebRequest,
        wsClass: WebSocket,
        localStorage: localStorage,
        sessionStorage: sessionStorage
    };
    return adapter;
}
exports.genAdapter = genAdapter;
```

**Comment by anti996sz** [comment]
tcb.init() 方法只能运行在浏览器中

**Comment by zhoujunpeng** [comment]
tcb-js-sdk本身是面向浏览器环境的，NativeScript的运行时并没有window对象。但是tcb-js-sdk支持通过适配器兼容非浏览器环境的运行平台，你可以根据https://www.npmjs.com/package/@cloudbase/adapter-interface 规定的接口开发NativeScript适配器。
